### ISSUE TITLE
Issues setting up a new SSO Dashboard

### ISSUE THREAD

**Issue by theburningmonk** [auth0-extensions/auth0-sso-dashboard-extension#79]
Hi, I followed the instructions [here](https://auth0.com/docs/extensions/single-sign-on-dashboard-extension) to set up a new SSO Dashboard, but it hasn't worked for me.

1. The URL in the docs (below) sees to be different to what the `Extensions` page is pointed at
![image](https://user-images.githubusercontent.com/546969/106394870-36ac3d80-63ff-11eb-9c9b-30e321406547.png)

If I go to the `Installed Extensions` page in my Auth0 portal, the `SSO Dashboard` extension points to this URL instead: https://dev-theburningmonk-ec.us.webtask.run/auth0-sso-dashboard/admins/login

and I assume the user login page would be at:
https://dev-theburningmonk-ec.us.webtask.run/auth0-sso-dashboard/login

2. If I visit the user login page I see this:
![image](https://user-images.githubusercontent.com/546969/106394910-8d197c00-63ff-11eb-9fa3-c9d36a7188c6.png)
even though I had followed the instructions and added both user and admin URLs to the allowed callback URLs:
![image](https://user-images.githubusercontent.com/546969/106394922-a5899680-63ff-11eb-999f-117a56c9d93a.png)

3. If I visit the admin login page then the Auth0 login page pops up, but when I enter my username and password to sign in I get a validation error
![image](https://user-images.githubusercontent.com/546969/106394943-c94cdc80-63ff-11eb-8ac5-d719df731259.png)

So, so far I've only managed to access the SSO dashboard from the `Extensions` page by clicking on the `SSO Dashboard` extension from the `Installed Extensions` page.
![image](https://user-images.githubusercontent.com/546969/106394965-e8e40500-63ff-11eb-8e95-00908e492674.png)

It feels like maybe I might have misconfigured something along the way, but I've followed the instructions step-by-step twice and have got the same result, so maybe the docs are out of date?

Any help would be much appreciated!

**Comment by NotMyself** [comment]
HI @theburningmonk,

It looks like the error page is telling you that you have a _callback URL mismatch_ for the tenant named **dev-theburningmonk-ec**.

At the bottom of that error page, you should see a box that looks like this.

![Screen Shot 2021-01-31 at 11 24 21 AM](https://user-images.githubusercontent.com/73120/106395384-e610f200-63b6-11eb-83d7-a863be0ff531.png)

Click the link and you will see some details like this.

![Screen Shot 2021-01-31 at 11 25 06 AM](https://user-images.githubusercontent.com/73120/106395420-0b9dfb80-63b7-11eb-8598-812900c2d9a6.png)

Make sure that the underlined URL in your message is added to the application's callback URLs setting in the tenant **dev-theburningmonk-ec**. Your URL will be different from mine.

That will get you past that error.

The second situation happens typically when you are attempting to use multiple Auth0 accounts and have crossed the streams so to speak. Meaning, you are logged into the dashboard with one account but attempted to authenticate to the extension with a different account. This situation can happen silently so that you do not even realize you are authenticating.

Have you tried it in an incognito window? If it works there, try clearing all your cookies for the auth0.com domain in your normal browser and reauthenticate.

Let me know if that helps.

**Comment by theburningmonk** [comment]
Thanks @NotMyself so looks both problems go back to the fact that the URLs mentioned in the docs are different to the one the extension created. In hindsight, I should have connected the dots 🤦 

What's mentioned in the docs: 
admin: https://YOU_TENANT.<REGION>8.webtask.io/auth0-sso-dashboard/admins/login
user: https://YOU_TENANT.<REGION>8.webtask.io/auth0-sso-dashboard/login

What the extension creates:
admin: https://dev-theburningmonk-ec.us.webtask.run/auth0-sso-dashboard/admins/login
user: https://dev-theburningmonk-ec.us.webtask.run/auth0-sso-dashboard/login

So once I changed the main SSO Dashboard application's `Allowed Callback URLs` to the URLs that the extension created then everything worked as expected.

I guess at some point the URL format changed but the docs weren't updated.

https://auth0.com/docs/extensions/single-sign-on-dashboard-extension
